version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - movie-picker-network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kevinhkr
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    networks:
      - movie-picker-network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=kevinhkr
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=kevinhkr
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on: 
      - mongodb
  backend:
    container_name: backend
    image: kevinhkr/movie-picker-backend
    build: backend
    networks:
      - movie-picker-network
    ports:
      - 5000:5000
  frontend:
    container_name: frontend
    image: kevinhkr/movie-picker-frontend
    build: frontend
    networks:
      - movie-picker-network
    ports:
      - 3000:3000
volumes:
  mongodb-data:
    driver: local
networks:
  movie-picker-network: